### ISSUE TITLE
Issue trying the example tutorial

### ISSUE THREAD

**Issue by kalwalt** [rust-cv/cv#28]
I'm trying the example [tutorial](https://rust-cv.github.io/tutorial/ch2-first-program.html) my code for the `main.rs` is:

```rust
use image::{DynamicImage, Rgba, GenericImageView};
use imageproc::drawing;
use rand::Rng;

fn main() {
    let src_image = image::open("res/0000000000.png").expect("failed to open image file");

    let mut rng = rand::thread_rng();

    let mut canvas = drawing::Blend(src_image.to_rgba());
    for _ in 0..50 {
        let x : i32 = rng.gen_range(0, src_image.width() - 1) as i32;
        let y : i32 = rng.gen_range(0, src_image.height() - 1) as i32;
        drawing::draw_cross_mut(&mut canvas, Rgba([0, 255, 255, 128]), x as i32, y as i32);
    }

    let out_img = DynamicImage::ImageRgba8(canvas.0);
    imgshow::imgshow(&out_img);
}
```
my `Cargo.toml` file:

```toml
[package]
name = "chapter2-first-program"
version = "0.1.0"
authors = ["Walter Perdan <github@kalwaltart.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imgshow = { git = "https://github.com/rust-cv/cv.git" }
image = "0.23.7"
imageproc = "0.21.0"
rand = "0.7.3"

```
image is in `res` folder;
When i run `cargo run`:

```
Running `target/debug/chapter2-first-program`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/walter/.cargo/registry/src/gith
ub.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/instance.rs:474:72
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
   2: core::panicking::panic
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:50
   3: core::option::Option<T>::unwrap
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:370
   4: wgpu_request_adapter
             at /home/walter/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/instance.rs
:474
   5: wgpu::Adapter::request
             at /home/walter/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.4.0/src/lib.rs:545
   6: <iced_wgpu::window::backend::Backend as iced_native::window::backend::Backend>::new
             at /home/walter/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_wgpu-0.2.3/src/window/backen
d.rs:21
 7: iced_winit::application::Application::run
             at /home/walter/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_winit-0.1.0/src/application.
rs:180
   8: iced::application::Application::run
             at /home/walter/.cargo/registry/src/github.com-1ecc6299db9ec823/iced-0.1.1/src/application.rs:201
   9: imgshow::imgshow
             at /home/walter/.cargo/git/checkouts/cv-f2802c299d0e3a2a/ed1a25e/imgshow/src/lib.rs:12
  10: chapter2_first_program::main
             at ./src/main.rs:18
  11: core::ops::function::FnOnce::call_once

```

my rustc version:
```
rustc --version
rustc 1.47.0 (18bf6b4f0 2020-10-07)

```
The image is in the `target/debug/res folder` Infact if i move it i receive the IoError:

 ```
cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `./chapter2-first-program`
thread 'main' panicked at 'failed to open image file: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/main.rs:6:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

What is wrong or what i did wrong? Sorry maybe is trivial for you but i'am a newbie with Rust... :slightly_smiling_face:

**Comment by kalwalt** [comment]
It seems that the issue is caused by iced see https://github.com/hecrj/iced/issues/398 https://github.com/hecrj/iced/issues/243. It is required to install Vulkan but i have an Nvidia Optimus graphics card, The [installation](https://github.com/felixdoerre/primus_vk#installation) seems a bit tricky...

**Comment by codec-abc** [comment]
Iced use wgpu which in turn uses Vulkan. So if you can't install a Vulkan driver you probably won't be able to get a interactive GUI running.

But if you want to play with Rust-cv for non interactive experiments you can somehow workaround this. When working on a chessboard detector on a computer without a Vulkan driver I saved the image to a .png and open it automatically with the [open crate.](https://crates.io/crates/open).

**Comment by kalwalt** [comment]
> Iced use wgpu which in turn uses Vulkan. So if you can't install a Vulkan driver you probably won't be able to get a interactive GUI running.
> 
> But if you want to play with Rust-cv for non interactive experiments you can somehow workaround this. When working on a chessboard detector on a computer without a Vulkan driver I saved the image to a .png and open it automatically with the [open crate](https://crates.io/crates/open).

Does it possible to use cv with another renderer? i was thinking about the sdl2 crate, What do you think?

**Comment by codec-abc** [comment]
It should be totally possible. Today, rust-cv is more about algorithms than visualization so it is not like you are missing something using sdl2.

**Comment by vadixidav** [comment]
To add to that, most of the things in `cv` were developed in absence of a GUI. We only added a few GUIs recently. wgpu does support metal on macs, DX11 and DX12 on Windows, and Vulkan on Linux. The reason that OpenGL is not supported is just that they have had a lot of difficulty making abstractions that are compatible with OpenGL vs all the other graphics libraries. While not a good solution, booting into Windows will allow you to run the demos since Vulkan support is not required on Windows.

**Comment by kalwalt** [comment]
Thank you @codec-abc  and @vadixidav for the feedback and help, I will purchase a new Pc soon, Without optimus tech, so probably will be easier from this point of view. In the meantime i will try `cv` with sdl2. I would also try to develop some little applications to be compiled with Wasm, but i have fear that will be hard for many reason... but this is another issue. I think we can close this, thank you again! :slightly_smiling_face:

**Comment by vadixidav** [comment]
@kalwalt Excellent. Also, you can ask more questions on the Discord. Although it is untested, much of Rust CV works with no_std, so you should be able to run it in wasm no problem, though we haven't tried that yet. Good luck!

**Comment by kalwalt** [comment]
> Excellent. Also, you can ask more questions on the Discord. 
good to know thanks!
> Although it is untested, much of Rust CV works with no_std, so you should be able to run it in wasm no problem, though we haven't tried that yet. Good luck!
This sound very interesting! i read somewhere on the rust-wasm docs that is easier to compile wasm code without no_std, I willl let you know when i will test some piece of code...
