### ISSUE TITLE
Change SVDs to use new nalgebra APIs

### ISSUE THREAD

**Issue by vadixidav** [rust-cv/cv#51]
`nalgebra` previously did not sort singular vectors in SVD. However, now it does by default, and it has an option to ask for them unordered as well. See <https://docs.rs/nalgebra/0.30.1/nalgebra/base/struct.Matrix.html#method.svd>.

In many places in the code, the SVD is is being explicitly sorted. Ideally, we would like to rely on this new behavior where the SVD is already sorted for us, so this old code can be changed and the sorting can be removed. Also, in any case where we were not sorting the singular values, we can change it to explicitly use the unordered version of the API: <https://docs.rs/nalgebra/0.30.1/nalgebra/base/struct.Matrix.html#method.svd_unordered>.

**Comment by xd009642** [comment]
Fixed in #56
